name: Deploy ASP.NET Core App to Azure Web App

on:
  push:
    branches:
      - main
      - Feature/commit

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Adjust to a stable version

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ByteMeAPI  # Specify the directory where your .csproj or .sln is located

    - name: Build project
      run: dotnet build --configuration Release
      working-directory: ByteMeAPI  # Specify the directory where your .csproj or .sln is located

    - name: Publish project
      run: dotnet publish --configuration Release --output ./output
      working-directory: ByteMeAPI  # Specify the directory where your .csproj or .sln is located

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ByteMeService
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./ByteMeAPI/output
